# Generated by Django 5.1.5 on 2025-02-11 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubeuser",
            name="owner_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="youtubeuser",
            name="phone_number",
            field=models.IntegerField(null=True),
        ),
    ]
