# Generated by Django 5.1.5 on 2025-02-12 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0004_youtubeuser_channel_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubeuser",
            name="channel_category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sic.category",
            ),
        ),
    ]
