# Generated by Django 5.1.5 on 2025-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0007_socialplatform_youtubeuser_facebook_access_token_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubeuser",
            name="youtube_channel_id",
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
