# Generated by Django 5.1.5 on 2025-02-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0008_alter_youtubeuser_youtube_channel_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="youtubeuser",
            name="youtube_channel_id",
        ),
    ]
