# Generated by Django 5.1.5 on 2025-02-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sic", "0009_remove_youtubeuser_youtube_channel_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="youtubeuser",
            name="facebook_access_token",
        ),
        migrations.RemoveField(
            model_name="youtubeuser",
            name="facebook_username",
        ),
        migrations.RemoveField(
            model_name="youtubeuser",
            name="instagram_access_token",
        ),
        migrations.RemoveField(
            model_name="youtubeuser",
            name="instagram_username",
        ),
        migrations.RemoveField(
            model_name="youtubeuser",
            name="x_access_token",
        ),
        migrations.RemoveField(
            model_name="youtubeuser",
            name="x_username",
        ),
        migrations.AddField(
            model_name="youtubeuser",
            name="facebook_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="youtubeuser",
            name="facebook_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="youtubeuser",
            name="instagram_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="youtubeuser",
            name="instagram_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="youtubeuser",
            name="x_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="youtubeuser",
            name="x_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
